/// # Key
/// The Key enum contains variants for all keys
pub enum Key {
    A,
    B,
    C,
    D,
    E,
    F,
    G,
    H,
    I,
    J,
    K,
    L,
    M,
    N,
    O,
    P,
    Q,
    R,
    S,
    T,
    U,
    V,
    W,
    X,
    Y,
    Z,
    Num0,
    Num1,
    Num2,
    Num3,
    Num4,
    Num5,
    Num6,
    Num7,
    Num8,
    Num9,
    Escape,
    LControl,
    LShift,
    LAlt,
    LSystem,
    RControl,
    RShift,
    RAlt,
    RSystem,
    Menu,
    LBracket,
    RBracket,
    Semicolon,
    Comma,
    Period,
    Quote,
    Slash,
    BackSlash,
    Grave,
    Equal,
    Dash,
    Space,
    Enter,
    BackSpace,
    Tab,
    PageUp,
    PageDown,
    End,
    Home,
    Insert,
    Delete,
    Add,
    Subtract,
    Multiply,
    Divide,
    Left,
    Right,
    Up,
    Down,
    Numpad0,
    Numpad1,
    Numpad2,
    Numpad3,
    Numpad4,
    Numpad5,
    Numpad6,
    Numpad7,
    Numpad8,
    Numpad9,
    F1,
    F2,
    F3,
    F4,
    F5,
    F6,
    F7,
    F8,
    F9,
    F10,
    F11,
    F12,
    F13,
    F14,
    F15,
    Pause,
    Unknown,
}

impl Key {
    /// # from_glfw_key
    /// Converts a glfw key to a ferrogame key
    pub fn from_glfw_key(key: glfw::Key) -> Key {
        match key {
            glfw::Key::A => Key::A,
            glfw::Key::B => Key::B,
            glfw::Key::C => Key::C,
            glfw::Key::D => Key::D,
            glfw::Key::E => Key::E,
            glfw::Key::F => Key::F,
            glfw::Key::G => Key::G,
            glfw::Key::H => Key::H,
            glfw::Key::I => Key::I,
            glfw::Key::J => Key::J,
            glfw::Key::K => Key::K,
            glfw::Key::L => Key::L,
            glfw::Key::M => Key::M,
            glfw::Key::N => Key::N,
            glfw::Key::O => Key::O,
            glfw::Key::P => Key::P,
            glfw::Key::Q => Key::Q,
            glfw::Key::R => Key::R,
            glfw::Key::S => Key::S,
            glfw::Key::T => Key::T,
            glfw::Key::U => Key::U,
            glfw::Key::V => Key::V,
            glfw::Key::W => Key::W,
            glfw::Key::X => Key::X,
            glfw::Key::Y => Key::Y,
            glfw::Key::Z => Key::Z,
            glfw::Key::Num0 => Key::Num0,
            glfw::Key::Num1 => Key::Num1,
            glfw::Key::Num2 => Key::Num2,
            glfw::Key::Num3 => Key::Num3,
            glfw::Key::Num4 => Key::Num4,
            glfw::Key::Num5 => Key::Num5,
            glfw::Key::Num6 => Key::Num6,
            glfw::Key::Num7 => Key::Num7,
            glfw::Key::Num8 => Key::Num8,
            glfw::Key::Num9 => Key::Num9,
            glfw::Key::Escape => Key::Escape,
            glfw::Key::LeftControl => Key::LControl,
            glfw::Key::LeftShift => Key::LShift,
            glfw::Key::LeftAlt => Key::LAlt,
            glfw::Key::LeftSuper => Key::LSystem,
            glfw::Key::RightControl => Key::RControl,
            glfw::Key::RightShift => Key::RShift,
            glfw::Key::RightAlt => Key::RAlt,
            glfw::Key::RightSuper => Key::RSystem,
            glfw::Key::Menu => Key::Menu,
            glfw::Key::LeftBracket => Key::LBracket,
            glfw::Key::RightBracket => Key::RBracket,
            glfw::Key::Semicolon => Key::Semicolon,
            glfw::Key::Comma => Key::Comma,
            glfw::Key::Period => Key::Period,
            glfw::Key::Apostrophe => Key::Quote,
            glfw::Key::Slash => Key::Slash,
            glfw::Key::Backslash => Key::BackSlash,
            glfw::Key::GraveAccent => Key::Grave,
            glfw::Key::Equal => Key::Equal,
            glfw::Key::Minus => Key::Dash,
            glfw::Key::Space => Key::Space,
            glfw::Key::Enter => Key::Enter,
            glfw::Key::Backspace => Key::BackSpace,
            glfw::Key::Tab => Key::Tab,
            glfw::Key::PageUp => Key::PageUp,
            glfw::Key::PageDown => Key::PageDown,
            glfw::Key::End => Key::End,
            glfw::Key::Home => Key::Home,
            glfw::Key::Insert => Key::Insert,
            glfw::Key::Delete => Key::Delete,
            glfw::Key::KpAdd => Key::Add,
            glfw::Key::KpSubtract => Key::Subtract,
            glfw::Key::KpMultiply => Key::Multiply,
            glfw::Key::KpDivide => Key::Divide,
            glfw::Key::Left => Key::Left,
            glfw::Key::Right => Key::Right,
            glfw::Key::Up => Key::Up,
            glfw::Key::Down => Key::Down,
            glfw::Key::F1 => Key::F1,
            glfw::Key::F2 => Key::F2,
            glfw::Key::F3 => Key::F3,
            glfw::Key::F4 => Key::F4,
            glfw::Key::F5 => Key::F5,
            glfw::Key::F6 => Key::F6,
            glfw::Key::F7 => Key::F7,
            glfw::Key::F8 => Key::F8,
            glfw::Key::F9 => Key::F9,
            glfw::Key::F10 => Key::F10,
            glfw::Key::F11 => Key::F11,
            glfw::Key::F12 => Key::F12,
            glfw::Key::F13 => Key::F13,
            glfw::Key::F14 => Key::F14,
            glfw::Key::F15 => Key::F15,
            glfw::Key::Pause => Key::Pause,
            _ => Key::Unknown,
        }
    }
} 

/// # MouseButton
/// The Mousebutton enum contains variants for all mouse buttons
pub enum MouseButton {
    Button1,
    Button2,
    Button3,
    Button4,
    Button5,
    Button6,
    Button7,
    Button8,
}

impl MouseButton {
    /// # from_glfw_mouse_button
    /// Converts a glfw mouse button to a ferrogame mouse button
    pub fn from_glfw_mouse_button(button: glfw::MouseButton) -> MouseButton {
        match button {
            glfw::MouseButton::Button1 => MouseButton::Button1,
            glfw::MouseButton::Button2 => MouseButton::Button2,
            glfw::MouseButton::Button3 => MouseButton::Button3,
            glfw::MouseButton::Button4 => MouseButton::Button4,
            glfw::MouseButton::Button5 => MouseButton::Button5,
            glfw::MouseButton::Button6 => MouseButton::Button6,
            glfw::MouseButton::Button7 => MouseButton::Button7,
            glfw::MouseButton::Button8 => MouseButton::Button8,
        }
    }
}